local locations =
{
    bulkDetonatorMiniBagLoc = {37.94, 0.97, 18.30},
    bulkDetonatorMiniBagRot = {359.50, 149.98, 0.23},
    infoCardLoc = {38.00, 1.00, 14.59},
    infoCardRot = {0.00, 179.86, 0.00}
}

local GUIDs =
{
    expansionBox = '619342',
    bulkDetonatorMiniBag = '8caff9',
    bulkDetonatorMini = 'd9404d',
    bulkDetonatorInfoCard = 'cf0871',
    bulkDetonatorSwarmCard = '004e7b'
}

function onLoad()
    self.clearButtons()

    if Global.call('getBulkDetonatorExpansionToggle') then
        ShowDisableExpansionButton()
    else
        ShowEnableExpansionButton()
    end

    expansionBox = getObjectFromGUID(GUIDs.expansionBox)
end

function ShowEnableExpansionButton()
    self.createButton(
        {
            click_function='EnableExpansion',
            function_owner=self,
            label="Enable\n Expansion",
            position={0.0,4.0,0.0},
            rotation={0.0,-90.0,90.0},
            width=1000,
            height=350,
            font_size=150,
            font_color='White',
            color='Green',
            tooltip='Enable Bulk Detonator - Mini Expansion'
        }
    )
end

function ShowDisableExpansionButton()
    self.createButton(
        {
            click_function='DisableExpansion',
            function_owner=self,
            label="Disable\n Expansion",
            position={0.0,4.0,0.0},
            rotation={0.0,-90.0,90.0},
            width=1000,
            height=350,
            font_size=150,
            font_color='White',
            color='Red',
            tooltip='Disable Bulk Detonator - Mini Expansion'
        }
    )
end

function EnableExpansion()
    self.clearButtons()
    ShowDisableExpansionButton()
    Global.Call('setBulkDetonatorExpansionToggle',true)

    params={
        bag = expansionBox,
        ID = GUIDs.bulkDetonatorMiniBag,
    }
    if Global.call('isInBag',params) then
        caveBag.takeObject({
            position = locations.bulkDetonatorMiniBagLoc,
            rotation = locations.bulkDetonatorMiniBagRot,
            guid = GUIDs.bulkDetonatorMiniBag,
            -- Lock tiles afer spawn
            callback="afterSpawnLock", callback_owner=Global
        })
    else
        print("Warning: Unable to set up Bulk Detonator bag, it's not in the expansion box")
    end
end

function DisableExpansion()
    self.clearButtons()
    ShowEnableExpansionButton()
    Global.Call('setBulkDetonatorExpansionToggle',false)
end
